name: firebase_food_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: 2.27.0
  firebase_auth: 4.17.8
  cloud_firestore: 4.15.7
  flutter_screenutil: 5.9.0
  firebase_storage: 11.6.8
  uuid: ^4.3.3
  intl: ^0.19.0
  cached_network_image: ^3.2.1
  image_picker: ^1.0.5
  flutter_native_splash: ^2.3.8
  flutter_local_notifications: ^11.0.0
  get_storage: ^2.0.3
  palette_generator: ^0.3.3+2
  flutter: 
    sdk: flutter
  flutter_timezone: ^1.0.8

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
  uses-material-design: true

flutter_native_splash: 
  color: '#ffffff'
  image: assets/images/logo2.png
  color_dark: '#121212'
  image_dark: assets/images/logo2.png
  android_12: 
    image: assets/images/logo2.png
    icon_background_color: '#ffffff'
    image_dark: assets/images/logo2.png
    icon_background_color_dark: '#121212'
  web: false

